image: golang:alpine3.15

install-dependencies:
  stage: build
  script:
    - bash ci-cd/install-dependencies.sh
test-kubectl:
  stage: test
  script:
    - echo "This job tests kubectl"
    - kubectl get pods