image: golang:alpine-3.15

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
test-kubectl:
  stage: test
  script:
    - echo "This job tests kubectl"
    - "kubectl get pods"