image: golang:alpine3.15

install-dependencies:
  stage: build
  script:
    - sh ci-cd/install-dependencies.sh
  artifacts:
    paths:
      - ~/.local/bin
    expire_in: 1 day
test-kubectl:
  stage: test
  script:
    - echo "This job tests kubectl"
    - kubectl get pods